#!/usr/bin/python

#This file contains a method to extract the information from the data 
#file generated by ./weather.sh and then generate a file which will
#be directly published which will be based on a particular protocol.




data = ["temp", "name", "humidity"]
def SHAS ():
			
	import fileinput, re
	for line in fileinput.input("../../data/weather.dat", inplace=True):
		print(line.replace(",", " , "))
	fileinput.close
	report = open ("../../data/weather.dat", "r")
	packet = open ("../../data/packet.dat", "w")
	for line in report:
		for word in line.split():
			#print word
			for  match in data:
				if match+"\"" in word:
					packet.write (word + "\n")
	return

SHAS()
import fileinput
for line in fileinput.input("../../data/packet.dat", inplace = True):
	print(line.replace("\"main\":{", ""))

fileinput.close


for line in fileinput.input("../../data/packet.dat", inplace = True):
	print(line.replace("\"main\":{", ""))

f = open ("../../data/packet.dat",'a')


f.write ('$')
f.close






















	#import re
	#file = open('../../data/weather.dat', 'r')
	## .lower() returns a version with all upper case characters replaced with lower case characters.
	#text = file.read().lower()
	#file.close()
	## replaces anything that is not a lowercase letter, a space, or an apostrophe with a space:
	#text = re.sub('[^a-z\ \']+', " ", text)
	#words = list(text.split())
	#print words
